# Generated by Django 5.2.12 on 2026-03-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Intento de login',
                'verbose_name_plural': 'Intentos de login',
                'ordering': ['-fecha'],
            },
        ),
    ]
