# Generated by Django 5.2.12 on 2026-03-09 03:23

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato: 12345678-9', max_length=12, null=True, unique=True, validators=[apps.accounts.validators.validar_rut_chileno]),
        ),
    ]
