# Generated by Django 5.2.12 on 2026-03-09 00:48

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones o detalles sobre este documento', null=True)),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio para el cumplimiento')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en el listado')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(help_text='Archivo del documento', upload_to=apps.documents.models.documento_upload_path)),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo antes del renombrado UUID', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('esta_vigente', models.BooleanField(default=True, help_text='Solo el documento más reciente por tipo estará vigente')),
                ('cliente', models.ForeignKey(help_text='Usuario cliente que subió el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento según el catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documents.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
