# Generated by Django 5.2.12 on 2026-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentorequerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del documento. Dejar en blanco si no vence.', null=True),
        ),
    ]
