# Generated by Django 5.2.12 on 2026-03-09 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('observacion', models.TextField(blank=True, help_text='Observaciones o motivo del rechazo', null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(help_text='Documento que fue evaluado', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='documents.documento')),
                ('evaluador', models.ForeignKey(help_text='Evaluador que realizó la revisión', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
